#!/usr/bin/python
#
# vcycle-cgi - Accept HTTP PUT requests of /etc/machineoutputs files
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-4. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

import os
import sys

import VCYCLE

if VCYCLE.readConf(requirePassword=False) is not None:
  print 'Status: 500 Internal Server Error (1)'
  print
  print VCYCLE.readConf(requirePassword=False)
  sys.exit(0)

try:
  (vmtypeName, hostName, subDirectory, fileName) = os.environ['REQUEST_URI'].replace('//','/').split('/')[1:5]
except:
  print 'Status: 404 Not Found'
  print
  sys.exit(0)

if (subDirectory != 'machineoutputs' or 
    not os.path.isdir('/var/lib/vcycle/mjf/' + vmtypeName + '/' + hostName + '/machineoutputs')):
  print 'Status: 404 Not Found'
  print
  sys.exit(0)


if (not 'SSL_CLIENT_S_DN' in os.environ or
    not vmtypeName in VCYCLE.vmtypes or 
    not 'x509dn' in VCYCLE.vmtypes[vmtypeName] or
    os.environ['SSL_CLIENT_S_DN'] != VCYCLE.vmtypes[vmtypeName]['x509dn']):
  print 'Status: 403 Forbidden'
  print
  sys.exit(0)

try:
  f = open('/var/lib/vcycle/mjf/' + vmtypeName + '/' + hostName + '/machineoutputs/' + fileName, 'w')
  f.write(sys.stdin.read())  
  f.close()
except:
  print 'Status: 500 Internal Server Error (2)'
  print
else:
  print 'Status: 200 OK'  
  print
