.TH VCYCLE-CGI 8 "Jan 2015" "vcycle-cgi" "Vcycle Manual"
.SH NAME
.B vcycle-cgi
\- Vcycle HTTPS CGI script
.SH SYNOPSIS
.B vcycle-cgi
.SH DESCRIPTION
.B vcycle-cgi
is a CGI scipt which is run from the Apache httpd daemon to allow VMs created by
Vcycle to write files to their $JOBOUTPUTS directory.

.SH CONFIGURATION FILES

See
.B
vcycle.conf(5)
for a description of the configuration files shared between vcycled and vcycle-cgi.

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

vcycle-cgi is part of Vcycle: http://www.gridpp.ac.uk/vcycle/
.SH "SEE ALSO"
.BR vcycle.conf(5),
.BR vcycled(8)
